name: .NET Core deploy

on: workflow_dispatch

jobs:
  deploy:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: self-hosted

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: MSIX Package
          path: C:\Users\Admin\Projects\runner\actions-runner\_work\DotNet-WebApp\DotNet-WebApp\WebApplication3\WebApplication3

