name: .NET Core deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: self-hosted

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: WebApplication3
          path: C:\Users\Admin\Projects\runner\actions-runner\_work\DotNet-WebApp\DotNet-WebApp\WebApplication3\WebApplication3

