name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: WebApplication3.sln                     
      Test_Project_Path: your-test-project-path                 
      Wap_Project_Directory: your-wap-project-directory-name    
      Wap_Project_Path: your-wap-project-path                   
      DOTNET_ROOT: C:\Program Files\dotnet
      Appx_Bundle: Always
      Appx_Bundle_Platforms: x86|x64
      Appx_Package_Build_Mode: StoreUpload

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore "WebApplication3/WebApplication3.sln"

    - name: Build the app package
      run: |
       & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe" "$env:Wap_Project_Path" /p:Configuration="$env:Configuration" /p:UapAppxPackageBuildMode="$env:Appx_Package_Build_Mode" /p:AppxBundle="$env:Appx_Bundle"
       shell: pwsh
       env:
       Solution_Name: WebApplication3.sln
       Test_Project_Path: your-test-project-path
       Wap_Project_Directory: your-wap-project-directory-name
       Wap_Project_Path: your-wap-project-path
       DOTNET_ROOT: C:\Program Files\dotnet
       Appx_Bundle: Always
       Appx_Bundle_Platforms: x86|x64
       Appx_Package_Build_Mode: StoreUpload


    - name: Remove the pfx
      run: Remove-Item -path $env:Wap_Project_Directory\GitHubActionsWorkflow.pfx

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: MSIX Package
        path: ${{ env.Wap_Project_Directory }}\AppPackages
