name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Solution_Name: WebApplication3.sln
      Test_Project_Path: your-test-project-path
      Wap_Project_Directory: your-wap-project-directory-name
      Wap_Project_Path: WebApplication3/WebApplication3
      DOTNET_ROOT: C:\Program Files\dotnet
      Appx_Bundle: Always
      Appx_Bundle_Platforms: x86|x64
      Appx_Package_Build_Mode: StoreUpload

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Restore Dependencies
        run: dotnet restore "WebApplication3/WebApplication3.sln"

      - name: Build the app package
        run: dotnet build "$env:Wap_Project_Path" --configuration "$env:Configuration"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MSIX Package
          path: ${{ env.Wap_Project_Path }}/AppPackages

      - name: Publish to GitHub Packages
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
          
      - name: Push package to GitHub Packages
        run: dotnet nuget push "WebApplication3/WebApplication3/AppPackages/YourPackage.nupkg" --source "https://nuget.pkg.github.com/pravesh-77/index.json"
        env:
          NUGET_VERSION: '5.x'
          NUGET_API_KEY: ${{ secrets.DOT_TOKEN }}
